require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WallMessagesController do

  # This should return the minimal set of attributes required to create a valid
  # WallMessage. As you add validations to WallMessage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all wall_messages as @wall_messages" do
      wall_message = WallMessage.create! valid_attributes
      get :index
      assigns(:wall_messages).should eq([wall_message])
    end
  end

  describe "GET show" do
    it "assigns the requested wall_message as @wall_message" do
      wall_message = WallMessage.create! valid_attributes
      get :show, :id => wall_message.id
      assigns(:wall_message).should eq(wall_message)
    end
  end

  describe "GET new" do
    it "assigns a new wall_message as @wall_message" do
      get :new
      assigns(:wall_message).should be_a_new(WallMessage)
    end
  end

  describe "GET edit" do
    it "assigns the requested wall_message as @wall_message" do
      wall_message = WallMessage.create! valid_attributes
      get :edit, :id => wall_message.id
      assigns(:wall_message).should eq(wall_message)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WallMessage" do
        expect {
          post :create, :wall_message => valid_attributes
        }.to change(WallMessage, :count).by(1)
      end

      it "assigns a newly created wall_message as @wall_message" do
        post :create, :wall_message => valid_attributes
        assigns(:wall_message).should be_a(WallMessage)
        assigns(:wall_message).should be_persisted
      end

      it "redirects to the created wall_message" do
        post :create, :wall_message => valid_attributes
        response.should redirect_to(WallMessage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved wall_message as @wall_message" do
        # Trigger the behavior that occurs when invalid params are submitted
        WallMessage.any_instance.stub(:save).and_return(false)
        post :create, :wall_message => {}
        assigns(:wall_message).should be_a_new(WallMessage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WallMessage.any_instance.stub(:save).and_return(false)
        post :create, :wall_message => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested wall_message" do
        wall_message = WallMessage.create! valid_attributes
        # Assuming there are no other wall_messages in the database, this
        # specifies that the WallMessage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WallMessage.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => wall_message.id, :wall_message => {'these' => 'params'}
      end

      it "assigns the requested wall_message as @wall_message" do
        wall_message = WallMessage.create! valid_attributes
        put :update, :id => wall_message.id, :wall_message => valid_attributes
        assigns(:wall_message).should eq(wall_message)
      end

      it "redirects to the wall_message" do
        wall_message = WallMessage.create! valid_attributes
        put :update, :id => wall_message.id, :wall_message => valid_attributes
        response.should redirect_to(wall_message)
      end
    end

    describe "with invalid params" do
      it "assigns the wall_message as @wall_message" do
        wall_message = WallMessage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WallMessage.any_instance.stub(:save).and_return(false)
        put :update, :id => wall_message.id, :wall_message => {}
        assigns(:wall_message).should eq(wall_message)
      end

      it "re-renders the 'edit' template" do
        wall_message = WallMessage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WallMessage.any_instance.stub(:save).and_return(false)
        put :update, :id => wall_message.id, :wall_message => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested wall_message" do
      wall_message = WallMessage.create! valid_attributes
      expect {
        delete :destroy, :id => wall_message.id
      }.to change(WallMessage, :count).by(-1)
    end

    it "redirects to the wall_messages list" do
      wall_message = WallMessage.create! valid_attributes
      delete :destroy, :id => wall_message.id
      response.should redirect_to(wall_messages_url)
    end
  end

end
